Bump version to 2.14 and reorganize script

diff --git a/highlight.SlackBuild b/highlight.SlackBuild
--- a/highlight.SlackBuild
+++ b/highlight.SlackBuild
@@ -7,22 +7,34 @@
 . ../slack-package.conf
 
 NAME=highlight
-VERSION=2.13
+VERSION=2.14
 BUILD=1
 ARCH=${ARCH:-i486}
 
-SRC=$TMP/$NAME-$VERSION
-if [ -d $SRC ]; then
-  rm -r $SRC
+TMP=${TMP:-/tmp}
+CWD=${CWD:-`pwd`}
+PKG_DIR=${PKG_DIR:-/tmp}
+
+if [ ! -e $TMP ]; then
+  mkdir -p $TMP # location to build the source
 fi
-PKG="$TMP/package-$NAME"
-if [ -d $PKG ]; then
-  rm -r $PKG
+
+SRC=$TMP/$NAME-$VERSION
+if [ -e $SRC -a -d $SRC ]; then
+  echo "Source directory '$SRC' already exists! Plaese, move it or remove it."
+  exit 1
+fi
+
+PKG=$TMP/package-$NAME
+if [ -e $PKG -a -d $PKG ]; then
+  echo "Package creation directory '$PKG' already exists! Please, move it or remove it."
+  exit 2
 fi
 mkdir -p $PKG
 
+# Extract and fix source
 cd $TMP
-tar -jxvf $CWD/$NAME-$VERSION.tar.bz2
+tar xvf $CWD/$NAME-$VERSION.tar.bz2
 cd $SRC
 fix_source
 
@@ -38,6 +50,7 @@ make DESTDIR=$PKG \
      doc_dir=/usr/doc/$NAME-$VERSION \
      install-gui || exit 4
 
+# Prepare
 bin_perms $PKG
 ( cd $PKG; strip_bin )
 gzip_man $PKG
@@ -54,14 +67,15 @@ install -m 644 $CWD/slack-required   $PKG/usr/src/slackbuilds/$NAME-$VERSION/sla
 install -m 644 $CWD/slack-suggests   $PKG/usr/src/slackbuilds/$NAME-$VERSION/slack-suggests
 install -m 644 $CWD/$NAME.SlackBuild $PKG/usr/src/slackbuilds/$NAME-$VERSION/$NAME.SlackBuild
 
+# Pack
 cd $PKG
 PKGNAME=$NAME-$VERSION-$ARCH-$BUILD$MYIN
-makepkg -l y -c n $PKG_DIR/$PKGNAME.tgz
+makepkg -l y -c n $PKG_DIR/$PKGNAME.txz
 cd $PKG_DIR
-md5sum $PKGNAME.tgz > $PKGNAME.tgz.md5
+md5sum $PKGNAME.txz > $PKGNAME.txz.md5
 cat $PKG/install/slack-desc > $PKGNAME.txt
 
-# Clean up
+# Clean up (optionally)
 if [ "$1" == "--cleanup" ]; then
   rm -r $SRC
   rm -r $PKG
